name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    # scheduling once every 3 hours
    - cron: "0 */3 * * *"

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify Last Update ğŸ‘»
        run: |
          d=`date +%s%N | cut -b1-13`
          echo $d > update.txt

      - name: Commit Changes ğŸ¥´
        run: |
          git config --local user.email "suluh.webdevelopers@hotmail.com"
          git config --local user.name "sooluh"
          git add --all

          msgs[0]="auto commit ğŸ˜‚"
          msgs[1]="auto commit ğŸ˜±"
          msgs[2]="auto commit ğŸ‘¿"
          msgs[3]="auto commit ğŸ’©"
          msgs[4]="auto commit ğŸ™"
          msgs[5]="auto commit ğŸ™ˆ"
          msgs[6]="auto commit ğŸ"
          msgs[7]="auto commit ğŸš€"

          rand=$[$RANDOM % ${#msgs[@]}]

          git commit -m "${msgs[$rand]}"

      - name: GitHub Push ğŸŒ 
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
