name: Reforestation ğŸŒ±

on:
  workflow_dispatch:
  push:
    branches: ['main']
  schedule:
    # https://crontab.guru/every-4-hours
    - cron: "0 */4 * * *"

jobs:
  reforestation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Modify Last Update ğŸ›¸
        run: |
          chmod +x ./reforestation/run.sh
          ./reforestation/run.sh

      - name: Commit Changes ğŸš©
        run: |
          git config --local user.email "20874779+sooluh@users.noreply.github.com"
          git config --local user.name "Torch"
          git add --all

          date=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m ":hourglass: $date"

      - name: GitHub Push ğŸš€
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
